---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r include=FALSE}
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, 
          y = ~n, 
          color = ~aisle, 
          type = "bar", 
          colors = "viridis") %>%
  layout(yaxis = list(title = "Number of Item Ordered"), xaxis = list(title = "Aisle"), showlegend=FALSE)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>%
  mutate(order_dow = factor(order_dow)) %>%
  mutate(order_dow = recode_factor(order_dow, 
                                   "0" = "Sunday",
                                   "1" = "Monday",
                                   "2" = "Tuesday",
                                   "3" = "Wednesday",
                                   "4" = "Thursday",
                                   "5" = "Friday",
                                   "6" = "Saturday")) %>%
  mutate(order_dow = fct_relevel(order_dow,"Sunday", after = Inf)) %>%
  group_by(order_dow,order_hour_of_day) %>%
  summarise(count = n()) %>%
  plot_ly(x = ~order_hour_of_day, 
          y = ~count, 
          type = "scatter",
          mode = "lines",
          color = ~order_dow,
          colors = "viridis",
          line = list(shape = "spline")) %>%
  layout(title = "Number of Order accross a Day", yaxis = list(title = "Number of Order"), xaxis = list(title = "Hour of Day"))
```

### Chart C

```{r}
instacart %>% 
  add_count(department) %>%
  filter(n > 1000) %>% 
  plot_ly(x = ~department, 
          y = ~order_hour_of_day, 
          type = "box", 
          color = ~department, 
          colors = "viridis") %>%
  layout(title = "Distribution of Ordering Time Fistribution over a Day", yaxis = list(title = "Hour of Day"), showlegend=FALSE)
```

